### ISSUE TITLE
server.database is not a function

### ISSUE THREAD

**Issue by doginthehat** [rosmo/sails-arangodb#11]
I'm trying to test out Sails with Arangodb using your connector. 

I've got a basic sails installation, nothing added except a call to sails generate api.

When I run `sails lift`, I get the following error:

```
An error has occured when trying to connect to ArangoDB:
/Volumes/WORK/test-sails/node_modules/sails-arangodb/lib/connection.js:410
      throw err;
      ^

TypeError: server.database is not a function
    at module.exports.ensureDB (/Volumes/WORK/test-sails/node_modules/sails-arangodb/lib/connection.js:26:9)
    at module.exports.getDb (/Volumes/WORK/test-sails/node_modules/sails-arangodb/lib/connection.js:44:16)
    at module.exports.connect (/Volumes/WORK/test-sails/node_modules/sails-arangodb/lib/connection.js:397:7)
    at Object.module.exports.create (/Volumes/WORK/test-sails/node_modules/sails-arangodb/lib/connection.js:418:14)
    at module.exports.getConn (/Volumes/WORK/test-sails/node_modules/sails-arangodb/lib/adapter.js:51:19)
    at Object.module.exports.adapter.registerConnection (/Volumes/WORK/test-sails/node_modules/sails-arangodb/lib/adapter.js:114:7)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:203:29
    at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:162:20
    at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:230:13
    at _arrayEach (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:81:9)
    at _each (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:72:13)
    at Object.async.forEachOf.async.eachOf (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:229:9)
    at Object.async.forEach.async.each (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:206:22)
    at Array.async.auto.registerConnections (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:176:13)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:590:38
    at _arrayEach (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:81:9)
```

I've added a `console.log` to ensureDB to dump the `server` variable and I guess this: 

```
Database {
  _connection: 
   Connection {
     config: 
      { url: 'http://localhost:8529',
        databaseName: '_system',
        arangoVersion: 20300,
        agentOptions: [Object],
        headers: [Object] },
     _request: [Function: request],
     promisify: [Function] },
  _api: 
   Route {
     _connection: 
      Connection {
        config: [Object],
        _request: [Function: request],
        promisify: [Function] },
     _path: '_api',
     _headers: undefined },
  name: '_system' }
```

Am I missing something?

**Comment by doginthehat** [comment]
Versions info:

```
sails -v
0.11.3
node -v
v4.1.1
npm -v
3.3.4
```

**Comment by gabriel-letarte** [comment]
I recently (about 1 week) took the ownership of this project. I was not able to run the original one but I am currently working on integrating `ArangoJS 4.1.0`. Take a look at the following branch: `convert-to-4.0.1`. This is still a work in progress but it should stabilize and make it to `master` in the next few weeks :)

**Comment by doginthehat** [comment]
@gabriel-letarte 

Thanks for the heads up. I'll give it a spin with the convert-to-4.0.1 branch.

**Comment by doginthehat** [comment]
Seems to work ok for the (very) brief test I did with the convert-to-4.0.1 branch :+1:

**Comment by doginthehat** [comment]
(after updating the connection setting, which had changed format)

**Comment by gabriel-letarte** [comment]
Im glad to hear that. I will close this issue once I merge `convert-to-4.0.1` to master and update the `README.md`

**Comment by gabriel-letarte** [comment]
The NPM module has been updated to `0.2.0`
https://www.npmjs.com/package/sails-arangodb
