### ISSUE TITLE
Not compatible with aqbjs versions > 1.11.0

### ISSUE THREAD

**Issue by hannupekka** [rosmo/sails-arangodb#7]
ArangoDB AQL query builder has made some changes that cause sails-arangodb to fail when connecting

```
error: Sending 500 ("Server Error") response:
 TypeError: undefined is not a function
    at module.exports.optionsToQuery (/.../node_modules/sails-arangodb/lib/connection.js:187:18)
    at module.exports.DbHelper.find (/.../node_modules/sails-arangodb/lib/connection.js:226:14)
    at Object.module.exports.adapter.find (/.../node_modules/sails-arangodb/lib/adapter.js:197:38)
    at module.exports.find (/.../node_modules/sails/node_modules/waterline/lib/waterline/adapter/dql.js:120:13)
    at _runOperation (/.../node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:408:29)
    at run (/.../node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:69:8)
    at bound.module.exports.find (/.../node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:264:16)
    at bound [as find] (/.../node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Deferred.exec (/.../node_modules/sails/node_modules/waterline/lib/waterline/query/deferred.js:501:16)
    at findRecords (/.../node_modules/sails/lib/hooks/blueprints/actions/find.js:47:9)
    at routeTargetFnWrapper (/.../node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/.../node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/.../node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at pass (/.../node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/.../node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/.../node_modules/sails/node_modules/express/lib/router/index.js:167:11) [TypeError: undefined is not a function]
```

Commit that breaks this: https://github.com/arangodb/aqbjs/commit/f3d8a6bfe421f3b6311fb610c3c3d453f11edd78

**Comment by rosmo** [comment]
Closed by #8.
